version: '3'
services:
  ingester:
    build: ./
    env_file: .env
    depends_on:
      - kafka
      - macd-tracker
  kafka:
    image: ches/kafka
    environment:
      - ZOOKEEPER_IP=zookeeper
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper:3.4
  influx:
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=main
      - INFLUXDB_WRITE_USER=user
      - INFLUXDB_WRITE_USER_PASSWORD=pass
    volumes:
      - influxdb:/var/lib/influxdb
  macd-tracker:
    image: msull92/macd-tracker:latest
    depends_on:
      - kafka
      - macd_redis
    environment:
      - KAFKA_ENDPOINT=kafka:9092
      - KAFKA_PRODUCER_TOPIC=macd-stats
      - KAFKA_CONSUMER_TOPIC=equity-quotes
      - KAFKA_CONSUMER_GROUP=macd-tracker
      - REDIS_ENDPOINT=macd_redis:6379
  quote-tracker:
    image: msull92/quote-tracker
    environment:
      - EQUITY_WATCHLIST=AAPL,ABBV,ABT,ACN,AGN,AIG,ALL,AMGN,AMZN,AXP,BA,BAC,BIIB,BK,BLK,BMY,C,CAT,CELG,CHTR,CL,CMCSA,COF,COP,COST,CSCO,CVS,CVX,DHR,DIS,DUK,DWDP,EMR,EXC,F,FB,FDX,FOX,GD,GE,GILD,GM,GOOG,GS,HAL,HD,HON,IBM,INTC,JNJ,JPM,KHC,KMI,KO,LLY,LMT,LOW,MA,MCD,MDLZ,MDT,MET,MMM,MO,MON,MRK,MS,MSFT,NEE,NKE,ORCL,OXY,PEP,PFE,PG,PM,PYPL,QCOM,RTN,SBUX,SLB,SO,SPG,T,TWX,TXN,UNH,UNP,UPS,USB,USD,UTX,V,VZ,WBA,WFC,WMT,XOM,ADSK,BAC,TWTR,SQ,USB,MSFT,AAPL,COF,CRM,AMZN,GRPN,GOOG,AMD,IBM,INTC,FB,MMM,NVDA,NFLX,ADSK,TSLA,PYPL,COST,EA,DIS,SBUX,UNH,BBY,TWLO
      - KAFKA_ENDPOINT=kafka:9092
      - KAFKA_PRODUCER_TOPIC=equity-quotes
  macd_redis:
    image: redis

volumes:
  influxdb:
